platform :ios, '10.0'

# 忽略引入库的所有警告（强迫症者的福音啊）
inhibit_all_warnings!

workspace 'HiChat.xcworkspace'


target 'HiChat' do
    pod 'Socket.IO-Client-Swift'
    pod 'SDWebImage'
    pod 'Toast'
    pod 'SVProgressHUD'
    pod 'M80AttributedLabel'
    pod 'TZImagePickerController'
    pod 'FMDB'
    pod 'AFNetworking'
    pod 'Masonry'
    pod 'MJRefresh'

    #pod 'SDCycleScrollView'
    pod 'MBProgressHUD'
    pod 'YYKit'
    #表情云
    pod 'BQMM'
    #键盘
    pod 'IQKeyboardManager'
    #高德地图相关SDK（无IDFA版）
    pod 'AMapLocation-NO-IDFA'
    pod 'AMapSearch-NO-IDFA'
    pod 'AMap2DMap-NO-IDFA'

    target 'HiChat' do
        project 'HiChat.xcodeproj'
        pod 'FMDB'
        pod 'Reachability'
        pod 'CocoaLumberjack'
        pod 'SSZipArchive'
        pod 'SVProgressHUD'
        pod 'Fabric'
        pod 'Crashlytics'
    end
    
    target 'HiChatKit' do
        project '../HiChatKit/HiChatKit.xcodeproj'
    end
end

